name: Build

on:
  push:
    branches: 
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: get_version
        name: Get Version
        uses: battila7/get-version-action@v2
      - name: Build
        uses: eskatos/gradle-command-action@v1
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
        with:
           arguments: build
           dependencies-cache-enabled: true
      - name: Release on tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: eskatos/gradle-command-action@v1
        with: 
          arguments: release "-PreleaseVersion=${{ steps.get_version.outputs.version }}"
          dependencies-cache-enabled: true
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/test-results/**/*.xml"
