name: Check PR

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: get_version
        name: Get Version
        uses: battila7/get-version-action@v2
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
           arguments: dependencyReport build
           dependencies-cache-enabled: true
      - name: Store Dependency Report
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: "**/build/reports/project/dependencies.txt"
