name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: get_version
        name: Get Version
        uses: battila7/get-version-action@v2
      - name: Release
        uses: eskatos/gradle-command-action@v1
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        with: 
          arguments: dependencyReport test publishToSonatype closeSonatypeStagingRepository
          # when release build is settled, switch to: arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
          dependencies-cache-enabled: true
      - name: Store Dependency Report
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: "**/build/reports/project/dependencies.txt"
      - name: Store HTML test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report-html
          path: "**/reports/tests/"
      - name: Store XML test report
        uses: actions/upload-artifact@v3
        with:
          name: test-results-xml
          path: "**/test-results/"
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/test-results/**/*.xml"
          